### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Uronic** [amuDev/amuJS#1]
Hello, plugin is spamming these errors:
[SM] Exception reported: Client x is not connected
[SM] Blaming: hns/amuJS.smx
[SM] Call stack trace:
[SM] [0] ClientCommand
[SM] [1] Line 2185, D:\dd\amuJS.sp::NumberThreePost
[SM] [2] Line 2158, D:\dd\amuJS.sp::Top3Check
[SM] [3] Line 2107, D:\dd\amuJS.sp::Top3CheckDelay

**Comment by amuDev** [comment]
Error has since been fixed in version 4.1.0
